using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.Xna.Framework;
using Xunit;
using Xunit.Abstractions;

namespace MTile.Tests.Sim;

// Integrity gates for the Zeus encounter (Stages "hill" + Levels/hill.json), which is
// now a 150-tile tower generated by scripts/gen-tower.py. Same shape as
// GauntletStageTests: run the real TerrainLoader over the real files, then run the real
// stage Populate and step the real Simulation.
//
// The things worth pinning are the ones that are silent when broken. A tower whose
// stair steps two tiles somewhere, or whose shaft has no doorway on one deck, loads
// without complaint and looks perfectly fine — it just cannot be climbed past the
// break, and you find that out by walking into it. So:
//
//   * the tower is actually 150 tiles tall, and the statue is standing ON the summit
//   * every stair column steps at most one tile, the whole way up
//   * every deck has an open doorway through the shaft (the switchback crosses there)
//   * all three laser attacks open within one schedule cycle, from the summit
public class ZeusHillTests(ITestOutputHelper output)
{
    // Mirrored from scripts/gen-tower.py. If the generator's constants change, these
    // must too — that is the point of asserting against them rather than against
    // whatever the files happen to contain.
    private const int GroundTileY = 13;
    private const int Height      = 150;
    private const int TopTileY    = GroundTileY - Height;    // -137, summit deck surface
    private const int LevelStep   = 15;
    private const int Levels      = Height / LevelStep;      // 10
    private const int ShaftHalf   = 3;
    private const int DeckHalf    = 19;
    private const int StairIn     = ShaftHalf + 2;   // 5  — landing column, at deck level
    private const int StairOut    = DeckHalf;        // 19 — rim column

    // Odd levels climb west; the player spawns on the western plain, so the first stair
    // has to be the one they walk into.
    private static int StairSide(int k) => k % 2 == 1 ? -1 : 1;

    // Topmost solid row of a column within one level's band. A plain top-down scan is
    // useless on a tower: every column is under a deck, so "the surface" globally is
    // always the summit. The stair is a local feature between two decks.
    private static int SurfaceInBand(ChunkMap chunks, int gtx, int topY, int bottomY)
    {
        for (int gty = topY; gty <= bottomY; gty++)
            if (Solid(chunks, gtx, gty)) return gty;
        return bottomY + 1;
    }

    private static readonly Vector2 ZeusSpawn = new(0f, TopTileY * Chunk.TileSize - 16f);

    private static int DeckTileY(int k) => GroundTileY - k * LevelStep;

    private static bool Solid(ChunkMap chunks, int gtx, int gty)
        => TileQuery.IsSolidAt(chunks, gtx * 16f + 8f, gty * 16f + 8f);

    // Topmost solid row in a column, scanning the whole tower band.
    private static int SurfaceTileY(ChunkMap chunks, int gtx)
    {
        for (int gty = TopTileY; gty <= GroundTileY; gty++)
            if (Solid(chunks, gtx, gty)) return gty;
        return GroundTileY;
    }

    private static string LevelsDir()
    {
        var d = new DirectoryInfo(AppContext.BaseDirectory);
        while (d != null)
        {
            string c = Path.Combine(d.FullName, "Levels");
            if (File.Exists(Path.Combine(c, "hill.json"))) return c;
            d = d.Parent;
        }
        return null;
    }

    private static ChunkMap LoadTower(string levels)
    {
        var chunks = new ChunkMap();
        TerrainLoader.Load(Path.Combine(levels, "hill.json"), chunks);
        return chunks;
    }

    [Fact]
    public void HillChunkFilesAreExactlySixteenBySixteen()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }

        foreach (var path in Directory.GetFiles(levels, "hill_*.txt"))
        {
            var lines = File.ReadAllLines(path);
            Assert.True(lines.Length >= Chunk.Size,
                $"{Path.GetFileName(path)} has {lines.Length} rows, expected {Chunk.Size}.");
            for (int i = 0; i < Chunk.Size; i++)
                Assert.True(lines[i].Length == Chunk.Size,
                    $"{Path.GetFileName(path)} row {i} is {lines[i].Length} chars, expected {Chunk.Size}.");
        }
    }

    [Fact]
    public void TowerIsOneHundredAndFiftyTilesTallWithASolidSummit()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = LoadTower(levels);

        // The summit deck the statue stands on, and open sky directly above it.
        Assert.True(Solid(chunks, 0, TopTileY), $"summit row {TopTileY} is not solid");
        Assert.False(Solid(chunks, 0, TopTileY - 1), $"row {TopTileY - 1} above the summit is solid");

        // 150 tiles from the ground plane to the summit, measured rather than assumed.
        int surface = SurfaceTileY(chunks, 0);
        Assert.Equal(TopTileY, surface);
        Assert.Equal(Height, GroundTileY - surface);

        // Every deck reaches its rim on the side that carries the next stair, and is two
        // tiles thick there — and is OPEN over its own stairwell on the other side. The
        // opening is not cosmetic: it is the headroom the climb runs through, and a deck
        // that quietly spans both rims walls its own stair off three columns short.
        for (int k = 1; k <= Levels; k++)
        {
            int dy = DeckTileY(k), side = StairSide(k);
            Assert.True(Solid(chunks, -side * DeckHalf, dy),     $"deck {k} missing at its walkable rim");
            Assert.True(Solid(chunks, -side * DeckHalf, dy + 1), $"deck {k} is only one tile thick");
            Assert.False(Solid(chunks, side * DeckHalf, dy),     $"deck {k}'s stairwell is closed over");
        }

        // The summit's parapet. Zeus's own bolt can vaporise it — it eats terrain — but
        // it has to be THERE at load, or the boss arena is an open ledge 150 tiles up and
        // the first knockback of any kind ends the fight. It also has to rise above the
        // summit row, which is the one place the generator's open-sky cutoff can silently
        // swallow it.
        int summitSide = StairSide(Levels);
        for (int d = 1; d <= 3; d++)
            Assert.True(Solid(chunks, -summitSide * DeckHalf, TopTileY - d),
                        $"summit parapet missing at row {TopTileY - d}");
        // ...and stop at the rim rather than running off as an endless wall.
        Assert.False(Solid(chunks, -summitSide * (DeckHalf + 2), TopTileY - 1),
                     "summit parapet extends past the rim");
    }

    // The climb. A stair column that steps two tiles is a wall, and the tower silently
    // dead-ends there — so this walks every stair the generator claims to have drawn and
    // holds it to the one-tile-per-column rule the old hill's slope was held to.
    [Fact]
    public void EveryStairStepsAtMostOneTile()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = LoadTower(levels);

        for (int k = 1; k <= Levels; k++)
        {
            int side = StairSide(k);
            int prev = DeckTileY(k - 1), dy = DeckTileY(k);
            for (int j = StairIn; j <= StairOut; j++)
            {
                int gtx  = side * j;
                int top  = SurfaceInBand(chunks, gtx, dy, prev);
                int want = prev - (StairOut + 1 - j);
                Assert.True(top == want,
                    $"level {k} stair column {gtx}: surface {top}, expected {want}");
            }
        }
    }

    // The doorways. The shaft runs the full height, so each deck is two disconnected
    // balconies unless something is punched through it — and the switchback crosses the
    // shaft on every single deck. Miss one and the climb stops there. The ground counts:
    // the first stair is on the far side of the shaft from the player's spawn.
    [Fact]
    public void EveryDeckHasAnOpenDoorwayThroughTheShaft()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = LoadTower(levels);

        for (int k = 0; k <= Levels; k++)
        {
            int dy = DeckTileY(k);
            for (int gtx = -ShaftHalf; gtx <= ShaftHalf; gtx++)
                for (int d = 1; d <= 3; d++)
                    Assert.False(Solid(chunks, gtx, dy - d),
                        $"deck {k}'s doorway is blocked at ({gtx},{dy - d})");
        }
    }

    [Fact]
    public void ZeusOpensAllThreeLaserAttacksWithinOneCycle()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = new ChunkMap();
        TerrainLoader.Load(Path.Combine(levels, "hill.json"), chunks);

        var stage = Stages.Get("hill");
        Assert.Equal("hill", stage.Name);

        // NOT stage.PlayerSpawn. The stage drops the player on the plain 150 tiles below,
        // which is both outside ZeusController.AlertRange (620px) and behind nine decks'
        // worth of blocked line of sight — the intended opening, since the climb belongs
        // to the birds. A do-nothing script there never provokes a shot.
        var vantage = new Vector2(-120f, TopTileY * Chunk.TileSize - 20f);
        var sim = new Simulation(chunks, vantage, stage.Populate);

        EnemyEntity zeus = null;
        foreach (var e in sim.Entities)
            if (e is EnemyEntity en && en.Kind == EntityKind.Zeus) zeus = en;
        Assert.NotNull(zeus);

        // Settled on the summit, not sunk into it or hovering.
        var spawnDrift = Vector2.Distance(zeus.Body.Position, ZeusSpawn);
        Assert.True(spawnDrift < 4f, $"Zeus spawned {spawnDrift:F1}px off the summit.");

        // Two full schedule cycles, so the sweep (which opens late and runs past
        // the cycle boundary) definitely gets a turn.
        // The target is PINNED to the vantage every frame. This is about the schedule and
        // the priorities — whether all three attacks get a turn — and letting the player
        // be knocked around confuses that with a separate question. Zeus's bolt knocks for
        // 520 and its beam eats terrain, so on a real summit the first hit shoves the
        // player off the rim (through the parapet it just vaporised) and they spend the
        // rest of the cycle falling 150 tiles, out of alert range: exactly one attack ever
        // opens and the schedule looks broken when it is fine. Holding the target still is
        // what makes this a test of Zeus rather than of the railing.
        var seen = new HashSet<string>();
        for (int f = 0; f < 2 * ZeusBeamWindows.CycleFrames; f++)
        {
            sim.Player.Body.Position = vantage;
            sim.Player.Body.Velocity = Vector2.Zero;
            sim.Step(default);
            string a = zeus.CurrentActionName;
            if (a.Length > 0) seen.Add(a);
        }
        output.WriteLine($"actions seen: {string.Join(",", seen)}");

        Assert.Contains("ZeusBoltAction",   seen);
        Assert.Contains("ZeusStrikeAction", seen);
        Assert.Contains("ZeusSweepAction",  seen);

        // The statue never moves off its post, whatever it fires.
        Assert.True(Vector2.Distance(zeus.Body.Position, ZeusSpawn) < 8f,
                    "Zeus wandered off the summit.");
    }

    // ZeusBeam is internal to MTile.Core; mirror the one constant this file needs
    // rather than opening the type up for a test.
    private static class ZeusBeamWindows
    {
        public const int CycleFrames = 600;
    }
}
