using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.Xna.Framework;
using Xunit;
using Xunit.Abstractions;

namespace MTile.Tests.Sim;

// Integrity gates for the Zeus encounter (Stages "hill" + Levels/hill.json), which is a
// 150-tile solid spire generated by scripts/gen-tower.py. Same shape as
// GauntletStageTests: run the real TerrainLoader over the real files, then run the real
// stage Populate and step the real Simulation.
//
// The things worth pinning are the ones that are silent when broken. A generator that
// drops a row, tapers the wrong way, or leaves the summit one tile lower than the statue
// is standing on loads without complaint and looks fine from the plain — you find it by
// climbing 150 tiles into it. So:
//
//   * the spire is actually 150 tiles tall, and the statue is standing ON the summit
//   * it is 37 across at the plain and 1 across at the tip, and solid in between
//   * the taper never steps more than one tile per three rows, and never widens going up
//   * nothing is built above the summit row, so the statue can see off its own tip
//   * the statue does not move, no matter what is done to it
//   * all three laser attacks open within one schedule cycle
public class ZeusHillTests(ITestOutputHelper output)
{
    // Mirrored from scripts/gen-tower.py. If the generator's constants change, these
    // must too — that is the point of asserting against them rather than against
    // whatever the files happen to contain.
    private const int GroundTileY = 13;
    private const int Height      = 150;
    private const int TopTileY    = GroundTileY - Height;    // -137, the summit surface
    private const int BaseHalf    = 18;                      // 37 tiles across
    private const int SpireHalf   = 5;                       // 11 across at the handover
    private const int TaperRise   = 3;                       // rows of rise per tile of run
    private const int SpireRise   = (BaseHalf - SpireHalf) * TaperRise;   // 39
    private const int TopRise     = Height - 1;                           // 149

    private static readonly Vector2 ZeusSpawn = new(0f, TopTileY * Chunk.TileSize - 16f);

    // The width the generator claims at row gty. Written out again rather than imported
    // because the generator is Python — this IS the mirrored contract.
    private static int HalfAt(int gty)
    {
        int rise = (GroundTileY - 1) - gty;
        if (rise < SpireRise) return BaseHalf - rise / TaperRise;
        int span = TopRise - SpireRise;
        return (SpireHalf * (TopRise - rise) * 2 + span) / (2 * span);
    }

    private static bool Solid(ChunkMap chunks, int gtx, int gty)
        => TileQuery.IsSolidAt(chunks, gtx * 16f + 8f, gty * 16f + 8f);

    // Topmost solid row in a column, scanning the whole tower band plus the sky above it.
    private static int SurfaceTileY(ChunkMap chunks, int gtx)
    {
        for (int gty = TopTileY - 4; gty <= GroundTileY; gty++)
            if (Solid(chunks, gtx, gty)) return gty;
        return GroundTileY;
    }

    // Half-width actually built at row gty: the outermost column that is solid.
    private static int MeasuredHalf(ChunkMap chunks, int gty)
    {
        int half = -1;
        for (int gtx = 0; gtx <= BaseHalf + 4; gtx++)
            if (Solid(chunks, gtx, gty)) half = gtx;
        return half;
    }

    private static string LevelsDir()
    {
        var d = new DirectoryInfo(AppContext.BaseDirectory);
        while (d != null)
        {
            string c = Path.Combine(d.FullName, "Levels");
            if (File.Exists(Path.Combine(c, "hill.json"))) return c;
            d = d.Parent;
        }
        return null;
    }

    private static ChunkMap LoadTower(string levels)
    {
        var chunks = new ChunkMap();
        TerrainLoader.Load(Path.Combine(levels, "hill.json"), chunks);
        return chunks;
    }

    [Fact]
    public void HillChunkFilesAreExactlySixteenBySixteen()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }

        foreach (var path in Directory.GetFiles(levels, "hill_*.txt"))
        {
            var lines = File.ReadAllLines(path);
            Assert.True(lines.Length >= Chunk.Size,
                $"{Path.GetFileName(path)} has {lines.Length} rows, expected {Chunk.Size}.");
            for (int i = 0; i < Chunk.Size; i++)
                Assert.True(lines[i].Length == Chunk.Size,
                    $"{Path.GetFileName(path)} row {i} is {lines[i].Length} chars, expected {Chunk.Size}.");
        }
    }

    [Fact]
    public void SpireIsOneHundredAndFiftyTilesTallWithASolidSummit()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = LoadTower(levels);

        // The summit the statue stands on, and open sky directly above it.
        Assert.True(Solid(chunks, 0, TopTileY), $"summit row {TopTileY} is not solid");
        Assert.False(Solid(chunks, 0, TopTileY - 1), $"row {TopTileY - 1} above the summit is solid");

        // 150 tiles from the ground plane to the summit, measured rather than assumed.
        int surface = SurfaceTileY(chunks, 0);
        Assert.Equal(TopTileY, surface);
        Assert.Equal(Height, GroundTileY - surface);

        // Solid stone the whole way down the axis: there is no interior any more, and a
        // hollow spire would be a very different (and much easier) climb.
        for (int gty = TopTileY; gty < GroundTileY; gty++)
            Assert.True(Solid(chunks, 0, gty), $"the spire is hollow at row {gty}");
    }

    // The silhouette. Every row is checked against the generator's width function, which
    // catches the ways a taper goes wrong at once: a wrong base, a step of the wrong size,
    // a tip that is not the width the summit is placed on, and — the one this shape exists
    // to prevent — a stretch that stops narrowing and stands up as a pillar. A pillar
    // hides its own face from its own tip, which is how Zeus ended up unable to see
    // anyone on the last hundred tiles of its own tower.
    [Fact]
    public void TaperNarrowsEveryStepFromThirtySevenWideToASingleTile()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = LoadTower(levels);

        // The widths the design is stated in: 2*half + 1 tiles across.
        Assert.Equal(37, 2 * BaseHalf  + 1);
        Assert.Equal(11, 2 * SpireHalf + 1);
        Assert.Equal(BaseHalf, MeasuredHalf(chunks, GroundTileY - 1));
        Assert.Equal(0,        MeasuredHalf(chunks, TopTileY));          // a one-tile tip

        int prev = int.MaxValue;
        for (int gty = GroundTileY - 1; gty >= TopTileY; gty--)
        {
            int half = MeasuredHalf(chunks, gty);
            Assert.True(half == HalfAt(gty),
                $"row {gty}: built half-width {half}, generator says {HalfAt(gty)}");
            // Monotone and one tile at a time: the face never bulges outward going up,
            // and never jumps two columns in a single row (which reads as a wall).
            Assert.True(half <= prev, $"row {gty} is wider than the row below it");
            Assert.True(prev == int.MaxValue || prev - half <= 1,
                $"row {gty} steps in {prev - half} tiles at once");
            prev = half;
            // ...and it is a filled cross-section, not a shell.
            Assert.True(Solid(chunks, half, gty) && Solid(chunks, -half, gty),
                $"row {gty} is not solid to both faces");
        }

        // And it never stalls: no width may run for more than a quarter of the height,
        // which is the pillar this shape replaced (111 rows of it) failing loudly.
        int run = 0, longest = 0;
        for (int gty = GroundTileY - 1; gty >= TopTileY; gty--)
        {
            run = HalfAt(gty) == HalfAt(gty + 1) ? run + 1 : 1;
            longest = Math.Max(longest, run);
        }
        output.WriteLine($"longest constant-width run: {longest} rows");
        Assert.True(longest < Height / 4, $"the spire stands up as a pillar for {longest} rows");
    }

    // Nothing above the tip. The old wide deck carried a rim parapet so the boss arena
    // was not an open ledge; an 11-wide summit cannot have one. The statue stands 16px
    // above the surface, so a rim wall would sit directly between it and anything off to
    // the side — and every Zeus laser gates on EnemyAim.HasLineOfSight, so a railing here
    // blinds the boss instead of fencing it in. Assert the tip stays bare, because a
    // "helpful" parapet is exactly the kind of thing that gets added back by hand.
    [Fact]
    public void NothingIsBuiltAboveTheSummitRow()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = LoadTower(levels);

        for (int gty = TopTileY - 4; gty < TopTileY; gty++)
            for (int gtx = -(BaseHalf + 4); gtx <= BaseHalf + 4; gtx++)
                Assert.False(Solid(chunks, gtx, gty),
                             $"something is built above the summit at ({gtx},{gty})");
    }

    // Rooted, and provably so. The statue's position is level geometry — PopulateHill
    // derives it from the summit row rather than writing a literal — so anything that
    // moves Zeus moves the boss fight off its own arena. The failure mode is a slow
    // drift that nobody notices until the statue is hanging beside the spire instead of
    // standing on it, which is why this asserts an exact position rather than a
    // tolerance: "barely moved" is the bug, just earlier.
    //
    // Both channels that can move a body are driven every frame — an impulse straight
    // into Velocity (what knockback is) and a sustained AppliedForce (what a force field
    // is) — and the player is pinned in Zeus's face the whole time so the statue is
    // firing, which means its own beams are eating the summit out from under it.
    [Fact]
    public void ZeusDoesNotMoveHoweverHardItIsShoved()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = LoadTower(levels);

        var vantage = new Vector2(-160f, TopTileY * Chunk.TileSize - 20f);
        var sim = new Simulation(chunks, vantage, Stages.Get("hill").Populate);

        EnemyEntity zeus = null;
        foreach (var e in sim.Entities)
            if (e is EnemyEntity en && en.Kind == EntityKind.Zeus) zeus = en;
        Assert.NotNull(zeus);
        Assert.True(zeus.Rooted, "Zeus is not rooted — the blueprint knob is off.");

        var start = zeus.Body.Position;
        Assert.Equal(ZeusSpawn, start);

        for (int f = 0; f < ZeusBeamWindows.CycleFrames; f++)
        {
            sim.Player.Body.Position = vantage;
            sim.Player.Body.Velocity = Vector2.Zero;

            zeus.Body.Velocity     = new Vector2(900f, -900f);
            zeus.Body.AppliedForce = new Vector2(4000f, -4000f);

            sim.Step(default);
            Assert.True(zeus.Body.Position == start,
                $"Zeus moved to {zeus.Body.Position} on frame {f} (spawned at {start}).");
        }

        // ...and it is genuinely at rest at the end, not merely back where it started.
        Assert.Equal(Vector2.Zero, zeus.Body.Velocity);
    }

    [Fact]
    public void ZeusOpensAllThreeLaserAttacksWithinOneCycle()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = LoadTower(levels);

        var stage = Stages.Get("hill");
        Assert.Equal("hill", stage.Name);

        // NOT stage.PlayerSpawn. The stage drops the player on the plain 150 tiles below,
        // which is both outside ZeusController.AlertRange (620px) and behind the spire's
        // own bulk — the intended opening, since the climb belongs to the birds. A
        // do-nothing script there never provokes a shot.
        //
        // Nor the summit itself, which is now 11 tiles across: standing on it puts the
        // player inside ZeusBoltAction.MinRange (80px) and ZeusSweepAction's (60px), so a
        // statue that is behaving perfectly opens exactly one attack. That suppression is
        // deliberate ("point blank is the reward for climbing the hill") and is not what
        // this test is about. The vantage is the last stretch of the climb instead: level
        // with the tip, 160px out from the axis, which is open air beside the needle and
        // inside every attack's band.
        var vantage = new Vector2(-160f, TopTileY * Chunk.TileSize - 20f);
        var sim = new Simulation(chunks, vantage, stage.Populate);

        EnemyEntity zeus = null;
        foreach (var e in sim.Entities)
            if (e is EnemyEntity en && en.Kind == EntityKind.Zeus) zeus = en;
        Assert.NotNull(zeus);

        // Standing exactly where PopulateHill put it.
        Assert.Equal(ZeusSpawn, zeus.Body.Position);

        // Two full schedule cycles, so the sweep (which opens late and runs past
        // the cycle boundary) definitely gets a turn.
        // The target is PINNED to the vantage every frame. This is about the schedule and
        // the priorities — whether all three attacks get a turn — and letting the player
        // be knocked around confuses that with a separate question. Zeus's bolt knocks for
        // 520 and its beam eats terrain, so on a real summit the first hit shoves the
        // player off the rim (through the parapet it just vaporised) and they spend the
        // rest of the cycle falling 150 tiles, out of alert range: exactly one attack ever
        // opens and the schedule looks broken when it is fine. Holding the target still is
        // what makes this a test of Zeus rather than of the railing.
        var seen = new HashSet<string>();
        for (int f = 0; f < 2 * ZeusBeamWindows.CycleFrames; f++)
        {
            sim.Player.Body.Position = vantage;
            sim.Player.Body.Velocity = Vector2.Zero;
            sim.Step(default);
            string a = zeus.CurrentActionName;
            if (a.Length > 0) seen.Add(a);
        }
        output.WriteLine($"actions seen: {string.Join(",", seen)}");

        Assert.Contains("ZeusBoltAction",   seen);
        Assert.Contains("ZeusStrikeAction", seen);
        Assert.Contains("ZeusSweepAction",  seen);

        // The statue never moves off its post, whatever it fires. Exactly, not nearly:
        // it is rooted, and ZeusDoesNotMoveHoweverHardItIsShoved is where that is put
        // under real pressure.
        Assert.True(zeus.Body.Position == ZeusSpawn,
                    $"Zeus wandered off the summit to {zeus.Body.Position}.");
    }

    // ── The spire is HARDENED rock, and the plain around it is not ───────────────
    //
    // The material is load-bearing design, not decoration: hardened is ungrabbable and
    // unplaceable (Tile.IsGrabbable / IsPlaceable special-case it) at 10x stone HP, so a
    // hardened spire is terrain the player fights WITHIN rather than with — the climb
    // can't be short-cut by ripping a staircase out of the face or peeling the tower into
    // throwable clods, which is what the block-throw kit does to any ordinary stone wall.
    //
    // Nothing else pins this. Every other assertion in this file goes through
    // TileQuery.IsSolidAt, which is blind to type, so regenerating the tower with STONE
    // would leave the whole suite green and silently hand the player back the shortcut.
    [Fact]
    public void SpireIsHardenedRock_AndTheGroundPlainIsNot()
    {
        string levels = LevelsDir();
        var chunks = LoadTower(levels);

        // Sample the spire body across its whole height, at the axis and on both faces.
        // The face columns are +/-half, NOT half-1: the spire dwindles to a single tile,
        // so half reaches 0 near the summit and half-1 would sample open sky and report a
        // material failure for what is really a geometry misunderstanding. At half == 0
        // the axis IS the whole tower, so the face samples collapse onto it harmlessly.
        int hardened = 0;
        for (int rise = 5; rise < Height; rise += 7)
        {
            int gty  = (GroundTileY - 1) - rise;
            int half = HalfAt(gty);
            foreach (int gtx in new[] { 0, half, -half })
            {
                Assert.Equal(TileState.Solid, chunks.GetCellState(gtx, gty));
                var type = chunks.GetCellType(gtx, gty);
                Assert.True(type == TileType.Hardened,
                    $"spire at ({gtx},{gty}) is {type}, not Hardened — was gen-tower.py "
                    + "regenerated with STONE? The climb depends on the face being ungrabbable.");
                hardened++;
            }
        }
        Assert.True(hardened > 50, $"sampled too little of the spire ({hardened} cells)");

        // The plain is ordinary workable terrain — the contrast is the point, and it is
        // what keeps the build/throw kit usable everywhere except the tower itself.
        Assert.Equal(TileState.Solid, chunks.GetCellState(BaseHalf + 12, GroundTileY));
        Assert.False(chunks.GetCellType(BaseHalf + 12, GroundTileY) == TileType.Hardened,
            "the plain around the tower must stay ordinary terrain, not hardened");
    }

    // ZeusBeam is internal to MTile.Core; mirror the one constant this file needs
    // rather than opening the type up for a test.
    private static class ZeusBeamWindows
    {
        public const int CycleFrames = 600;
    }
}
