using System;
using System.Collections.Generic;
using System.IO;
using Microsoft.Xna.Framework;
using Xunit;
using Xunit.Abstractions;

namespace MTile.Tests.Sim;

// Integrity gates for the Zeus encounter (Stages "hill" + Levels/hill.json), which is a
// 150-tile solid spire generated by scripts/gen-tower.py. Same shape as
// GauntletStageTests: run the real TerrainLoader over the real files, then run the real
// stage Populate and step the real Simulation.
//
// The things worth pinning are the ones that are silent when broken. A generator that
// drops a row, tapers the wrong way, or leaves the summit one tile lower than the statue
// is standing on loads without complaint and looks fine from the plain — you find it by
// climbing 150 tiles into it. So:
//
//   * the spire is actually 150 tiles tall, and the statue is standing ON the summit
//   * it is 37 across at the plain, 11 across in the needle, and solid in between
//   * the taper never steps more than one tile per three rows, and never widens going up
//   * nothing is built above the summit row, so the statue can see off its own tip
//   * all three laser attacks open within one schedule cycle
public class ZeusHillTests(ITestOutputHelper output)
{
    // Mirrored from scripts/gen-tower.py. If the generator's constants change, these
    // must too — that is the point of asserting against them rather than against
    // whatever the files happen to contain.
    private const int GroundTileY = 13;
    private const int Height      = 150;
    private const int TopTileY    = GroundTileY - Height;    // -137, the summit surface
    private const int BaseHalf    = 18;                      // 37 tiles across
    private const int SpireHalf   = 5;                       // 11 tiles across
    private const int TaperRise   = 3;                       // rows of rise per tile of run

    private static readonly Vector2 ZeusSpawn = new(0f, TopTileY * Chunk.TileSize - 16f);

    // The width the generator claims at row gty. Written out again rather than imported
    // because the generator is Python — this IS the mirrored contract.
    private static int HalfAt(int gty)
        => Math.Max(SpireHalf, BaseHalf - ((GroundTileY - 1) - gty) / TaperRise);

    private static bool Solid(ChunkMap chunks, int gtx, int gty)
        => TileQuery.IsSolidAt(chunks, gtx * 16f + 8f, gty * 16f + 8f);

    // Topmost solid row in a column, scanning the whole tower band plus the sky above it.
    private static int SurfaceTileY(ChunkMap chunks, int gtx)
    {
        for (int gty = TopTileY - 4; gty <= GroundTileY; gty++)
            if (Solid(chunks, gtx, gty)) return gty;
        return GroundTileY;
    }

    // Half-width actually built at row gty: the outermost column that is solid.
    private static int MeasuredHalf(ChunkMap chunks, int gty)
    {
        int half = -1;
        for (int gtx = 0; gtx <= BaseHalf + 4; gtx++)
            if (Solid(chunks, gtx, gty)) half = gtx;
        return half;
    }

    private static string LevelsDir()
    {
        var d = new DirectoryInfo(AppContext.BaseDirectory);
        while (d != null)
        {
            string c = Path.Combine(d.FullName, "Levels");
            if (File.Exists(Path.Combine(c, "hill.json"))) return c;
            d = d.Parent;
        }
        return null;
    }

    private static ChunkMap LoadTower(string levels)
    {
        var chunks = new ChunkMap();
        TerrainLoader.Load(Path.Combine(levels, "hill.json"), chunks);
        return chunks;
    }

    [Fact]
    public void HillChunkFilesAreExactlySixteenBySixteen()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }

        foreach (var path in Directory.GetFiles(levels, "hill_*.txt"))
        {
            var lines = File.ReadAllLines(path);
            Assert.True(lines.Length >= Chunk.Size,
                $"{Path.GetFileName(path)} has {lines.Length} rows, expected {Chunk.Size}.");
            for (int i = 0; i < Chunk.Size; i++)
                Assert.True(lines[i].Length == Chunk.Size,
                    $"{Path.GetFileName(path)} row {i} is {lines[i].Length} chars, expected {Chunk.Size}.");
        }
    }

    [Fact]
    public void SpireIsOneHundredAndFiftyTilesTallWithASolidSummit()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = LoadTower(levels);

        // The summit the statue stands on, and open sky directly above it.
        Assert.True(Solid(chunks, 0, TopTileY), $"summit row {TopTileY} is not solid");
        Assert.False(Solid(chunks, 0, TopTileY - 1), $"row {TopTileY - 1} above the summit is solid");

        // 150 tiles from the ground plane to the summit, measured rather than assumed.
        int surface = SurfaceTileY(chunks, 0);
        Assert.Equal(TopTileY, surface);
        Assert.Equal(Height, GroundTileY - surface);

        // Solid stone the whole way down the axis: there is no interior any more, and a
        // hollow spire would be a very different (and much easier) climb.
        for (int gty = TopTileY; gty < GroundTileY; gty++)
            Assert.True(Solid(chunks, 0, gty), $"the spire is hollow at row {gty}");
    }

    // The silhouette. Every row is checked against the generator's width function, which
    // catches the three ways a taper goes wrong at once: a wrong base, a step of the
    // wrong size, and a needle that is not the width the flock lanes are measured from.
    [Fact]
    public void TaperIsThreeRiseToOneRunFromBaseToNeedle()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = LoadTower(levels);

        // The two widths the design is stated in: 2*half + 1 tiles across.
        Assert.Equal(37, 2 * BaseHalf  + 1);
        Assert.Equal(11, 2 * SpireHalf + 1);
        Assert.Equal(BaseHalf,  MeasuredHalf(chunks, GroundTileY - 1));
        Assert.Equal(SpireHalf, MeasuredHalf(chunks, TopTileY));

        int prev = int.MaxValue;
        for (int gty = GroundTileY - 1; gty >= TopTileY; gty--)
        {
            int half = MeasuredHalf(chunks, gty);
            Assert.True(half == HalfAt(gty),
                $"row {gty}: built half-width {half}, generator says {HalfAt(gty)}");
            // Monotone and one tile at a time: the face never bulges outward going up,
            // and never jumps two columns in a single row (which reads as a wall).
            Assert.True(half <= prev, $"row {gty} is wider than the row below it");
            Assert.True(prev == int.MaxValue || prev - half <= 1,
                $"row {gty} steps in {prev - half} tiles at once");
            prev = half;
            // ...and it is a filled cross-section, not a shell.
            Assert.True(Solid(chunks, half, gty) && Solid(chunks, -half, gty),
                $"row {gty} is not solid to both faces");
        }

        // The taper covers exactly the rise the ratio implies, and the needle is the rest.
        int needleRise = (GroundTileY - 1) - TopTileY - (BaseHalf - SpireHalf) * TaperRise;
        output.WriteLine($"taper {(BaseHalf - SpireHalf) * TaperRise} rows, needle {needleRise} rows");
        Assert.True(needleRise > 0, "the taper runs past the summit");
    }

    // Nothing above the tip. The old wide deck carried a rim parapet so the boss arena
    // was not an open ledge; an 11-wide summit cannot have one. The statue stands 16px
    // above the surface, so a rim wall would sit directly between it and anything off to
    // the side — and every Zeus laser gates on EnemyAim.HasLineOfSight, so a railing here
    // blinds the boss instead of fencing it in. Assert the tip stays bare, because a
    // "helpful" parapet is exactly the kind of thing that gets added back by hand.
    [Fact]
    public void NothingIsBuiltAboveTheSummitRow()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = LoadTower(levels);

        for (int gty = TopTileY - 4; gty < TopTileY; gty++)
            for (int gtx = -(BaseHalf + 4); gtx <= BaseHalf + 4; gtx++)
                Assert.False(Solid(chunks, gtx, gty),
                             $"something is built above the summit at ({gtx},{gty})");
    }

    [Fact]
    public void ZeusOpensAllThreeLaserAttacksWithinOneCycle()
    {
        var levels = LevelsDir();
        if (levels == null) { output.WriteLine("Levels/ not found — skipping."); return; }
        var chunks = LoadTower(levels);

        var stage = Stages.Get("hill");
        Assert.Equal("hill", stage.Name);

        // NOT stage.PlayerSpawn. The stage drops the player on the plain 150 tiles below,
        // which is both outside ZeusController.AlertRange (620px) and behind the spire's
        // own bulk — the intended opening, since the climb belongs to the birds. A
        // do-nothing script there never provokes a shot.
        //
        // Nor the summit itself, which is now 11 tiles across: standing on it puts the
        // player inside ZeusBoltAction.MinRange (80px) and ZeusSweepAction's (60px), so a
        // statue that is behaving perfectly opens exactly one attack. That suppression is
        // deliberate ("point blank is the reward for climbing the hill") and is not what
        // this test is about. The vantage is the last stretch of the climb instead: level
        // with the tip, 160px out from the axis, which is open air beside the needle and
        // inside every attack's band.
        var vantage = new Vector2(-160f, TopTileY * Chunk.TileSize - 20f);
        var sim = new Simulation(chunks, vantage, stage.Populate);

        EnemyEntity zeus = null;
        foreach (var e in sim.Entities)
            if (e is EnemyEntity en && en.Kind == EntityKind.Zeus) zeus = en;
        Assert.NotNull(zeus);

        // Settled on the summit, not sunk into it or hovering.
        var spawnDrift = Vector2.Distance(zeus.Body.Position, ZeusSpawn);
        Assert.True(spawnDrift < 4f, $"Zeus spawned {spawnDrift:F1}px off the summit.");

        // Two full schedule cycles, so the sweep (which opens late and runs past
        // the cycle boundary) definitely gets a turn.
        // The target is PINNED to the vantage every frame. This is about the schedule and
        // the priorities — whether all three attacks get a turn — and letting the player
        // be knocked around confuses that with a separate question. Zeus's bolt knocks for
        // 520 and its beam eats terrain, so on a real summit the first hit shoves the
        // player off the rim (through the parapet it just vaporised) and they spend the
        // rest of the cycle falling 150 tiles, out of alert range: exactly one attack ever
        // opens and the schedule looks broken when it is fine. Holding the target still is
        // what makes this a test of Zeus rather than of the railing.
        var seen = new HashSet<string>();
        for (int f = 0; f < 2 * ZeusBeamWindows.CycleFrames; f++)
        {
            sim.Player.Body.Position = vantage;
            sim.Player.Body.Velocity = Vector2.Zero;
            sim.Step(default);
            string a = zeus.CurrentActionName;
            if (a.Length > 0) seen.Add(a);
        }
        output.WriteLine($"actions seen: {string.Join(",", seen)}");

        Assert.Contains("ZeusBoltAction",   seen);
        Assert.Contains("ZeusStrikeAction", seen);
        Assert.Contains("ZeusSweepAction",  seen);

        // The statue never moves off its post, whatever it fires.
        Assert.True(Vector2.Distance(zeus.Body.Position, ZeusSpawn) < 8f,
                    "Zeus wandered off the summit.");
    }

    // ZeusBeam is internal to MTile.Core; mirror the one constant this file needs
    // rather than opening the type up for a test.
    private static class ZeusBeamWindows
    {
        public const int CycleFrames = 600;
    }
}
