// <auto-generated>
//   Regenerate with:  pwsh scripts/sync-sounds.ps1
//   Source of truth is the files in Assets/Sounds/*.ogg — do not hand-edit.
//
//   This is a generated C# table rather than a runtime manifest file on purpose: the
//   WASM host cannot enumerate a content directory, and a compile-time table needs no
//   IO on either backend.
// </auto-generated>

namespace MTile;

public static class SoundManifest
{
    // (stem, variant count). Count 0 means "one unnumbered file", <stem>.ogg.
    public static readonly (string Stem, int Variants)[] Entries =
    {
        ("dev_tone", 0),
        ("double_jump", 1),
        ("eruption", 1),
        ("footstep", 2),
        ("grunt", 1),
        ("hit_connect", 7),
        ("jump", 1),
        ("swing", 2),
        ("throw", 1),
        ("tile_break", 1),
        ("tile_place", 1),
    };
}
