<#
.SYNOPSIS
  Wire the built sound clips in Assets/Sounds into the game.

.DESCRIPTION
  Scans Assets/Sounds/*.ogg, then regenerates two things so a new clip needs no
  hand-editing anywhere:

    1. The GENERATED SOUNDS region of Content/Content.mgcb — one pipeline entry per
       clip, built out-of-tree from ../Assets/Sounds and mapped to the asset name
       "Sounds/<stem>". Both toolchains (MonoGame 3.8.4.1 desktop, KNI 4.1.9001 web)
       have OggImporter + SoundEffectProcessor, so the same entries serve both.
    2. Audio/SoundManifest.g.cs — the compile-time (stem, variant count) table
       SoundBank loads from. Generated rather than read at runtime because the WASM
       host cannot enumerate a content directory.

  Naming: <stem>.ogg for a single clip, or <stem>_01.ogg, <stem>_02.ogg, … for
  round-robin variants. That is exactly what build-sfx.ps1 -Name <stem> produces.

  A stem with no matching entry in SoundKind is reported — it will build but nothing
  will ever play it until a SoundKind + stem exist.

.EXAMPLE
  pwsh scripts/build-sfx.ps1 -Name tile_break   # Audio/raw -> Assets/Sounds/*.ogg
  pwsh scripts/sync-sounds.ps1                  # -> mgcb entries + manifest
  dotnet run --project MTile.Desktop
#>
[CmdletBinding()]
param(
    [string]$SoundDir = "Assets/Sounds",
    [string]$Mgcb     = "Content/Content.mgcb",
    [string]$Manifest = "Audio/SoundManifest.g.cs",
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$BeginMark = '#--------------------------- GENERATED SOUNDS -------------------------------#'
$EndMark   = '#------------------------- END GENERATED SOUNDS -----------------------------#'

if (-not (Test-Path $SoundDir)) {
    Write-Host "no $SoundDir — nothing to sync" -ForegroundColor Yellow
    return
}

$clips = Get-ChildItem $SoundDir -Filter *.ogg -File | Sort-Object Name
Write-Host "== sync-sounds: $($clips.Count) clip(s) in $SoundDir ==" -ForegroundColor Cyan

# Group by stem: trailing _NN is a variant index, anything else is the whole stem.
$groups = @{}
foreach ($c in $clips) {
    $base = [IO.Path]::GetFileNameWithoutExtension($c.Name)
    if ($base -match '^(?<stem>.+)_(?<n>\d{2})$') { $stem = $Matches.stem; $numbered = $true }
    else                                          { $stem = $base;        $numbered = $false }
    if (-not $groups.ContainsKey($stem)) { $groups[$stem] = [pscustomobject]@{ Numbered = 0; Bare = $false } }
    if ($numbered) { $groups[$stem].Numbered++ } else { $groups[$stem].Bare = $true }
}

# Cross-check against the SoundKind stem table so typos surface here, not as silence.
# Stems are derived from the SoundKind enum names (PascalCase -> snake_case), the same
# rule SoundKinds.BuildStems applies at runtime.
$known = @()
if (Test-Path 'Audio/SoundKind.cs') {
    $src = Get-Content 'Audio/SoundKind.cs' -Raw
    if ($src -match '(?s)enum\s+SoundKind\s*\{(?<body>.*?)\}') {
        $body = $Matches.body -replace '//[^\r\n]*', ''
        $known = [regex]::Matches($body, '(?m)^\s*([A-Za-z][A-Za-z0-9]*)\s*(?:=\s*\d+\s*)?,') |
                 ForEach-Object { $_.Groups[1].Value } |
                 Where-Object { $_ -ne 'None' } |
                 ForEach-Object { ($_ -creplace '(?<!^)([A-Z])', '_$1').ToLowerInvariant() }
    }
}

# ── mgcb entries ────────────────────────────────────────────────────────────────
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add($BeginMark)
$lines.Add('# Written by scripts/sync-sounds.ps1 — do not hand-edit; your changes will be lost.')
$lines.Add('')
foreach ($c in $clips) {
    $stem = [IO.Path]::GetFileNameWithoutExtension($c.Name)
    $lines.Add("#begin ../$SoundDir/$($c.Name)")
    $lines.Add('/importer:OggImporter')
    $lines.Add('/processor:SoundEffectProcessor')
    $lines.Add('/processorParam:Quality=Best')
    $lines.Add("/build:../$SoundDir/$($c.Name);Sounds/$stem.xnb")
    $lines.Add('')
}
$lines.Add($EndMark)
$generated = ($lines -join "`n")

$mgcbText = Get-Content $Mgcb -Raw
$pattern  = "(?s)" + [regex]::Escape($BeginMark) + ".*?" + [regex]::Escape($EndMark)
if ($mgcbText -match $pattern) { $newMgcb = [regex]::Replace($mgcbText, $pattern, { $generated }) }
else                           { $newMgcb = $mgcbText.TrimEnd() + "`n`n" + $generated + "`n" }

# ── manifest ────────────────────────────────────────────────────────────────────
$entries = foreach ($stem in ($groups.Keys | Sort-Object)) {
    $g = $groups[$stem]
    $count = if ($g.Numbered -gt 0) { $g.Numbered } else { 0 }
    '        ("{0}", {1}),' -f $stem, $count
}
$manifestText = @"
// <auto-generated>
//   Regenerate with:  pwsh scripts/sync-sounds.ps1
//   Source of truth is the files in $SoundDir/*.ogg — do not hand-edit.
//
//   This is a generated C# table rather than a runtime manifest file on purpose: the
//   WASM host cannot enumerate a content directory, and a compile-time table needs no
//   IO on either backend.
// </auto-generated>

namespace MTile;

public static class SoundManifest
{
    // (stem, variant count). Count 0 means "one unnumbered file", <stem>.ogg.
    public static readonly (string Stem, int Variants)[] Entries =
    {
$($entries -join "`n")
    };
}
"@

foreach ($stem in ($groups.Keys | Sort-Object)) {
    $g = $groups[$stem]
    $n = if ($g.Numbered -gt 0) { "$($g.Numbered) variant(s)" } else { "single" }
    $flag = if ($known -contains $stem) { ' ' } else { '?' }
    $color = if ($known -contains $stem) { 'Green' } else { 'Yellow' }
    Write-Host ("  {0} {1,-24} {2}" -f $flag, $stem, $n) -ForegroundColor $color
}
$unknown = $groups.Keys | Where-Object { $known -notcontains $_ }
if ($unknown) {
    Write-Host "  ? = no SoundKind maps to this stem; it will build but never play." -ForegroundColor Yellow
    Write-Host "      Add an enum entry + stem in Audio/SoundKind.cs." -ForegroundColor Yellow
}

if ($DryRun) { Write-Host "-DryRun: nothing written" -ForegroundColor DarkGray; return }

$newMgcb      | Set-Content $Mgcb      -Encoding utf8 -NoNewline
$manifestText | Set-Content $Manifest  -Encoding utf8
Write-Host "wrote $Mgcb and $Manifest" -ForegroundColor Green
